import 'paint_content.dart';
import 'simple_line.dart';
import 'smooth_line.dart';
import 'straight_line.dart';
import 'rectangle.dart';
import 'circle.dart';
import 'triangle.dart';
import 'eraser.dart';
import 'lasso.dart';
import 'text.dart';
import 'shape_sticker.dart';
import 'group.dart';
import 'fill.dart';
import 'clipped.dart';
import 'eraser_hole.dart';
import 'eyedropper.dart';
import 'blur.dart';
import 'smudge.dart';
import 'image.dart';
import 'empty_content.dart';
import '../ruler/mirror_content.dart';
import '../ruler/radial_content.dart';
import 'extra_shapes.dart';
import 'shapes.dart';
import 'dashed_line.dart';
import 'dotted_line.dart';
import 'highlighter_line.dart';
import 'image_tip_brush.dart';
import 'shape_brush_line.dart';
import 'tip_brush.dart';
import 'stroke_recolor.dart';
import 'shape_fill.dart';
import 'preset_strokes.dart';
import 'stroke_styles.dart';

PaintContent? decodePaintContent(String type, Map<String, dynamic> data, [List<PaintContent>? history]) {
  switch (type) {
    case 'SimpleLine':
      // Backward compatibility: check if it's the old freehand SimpleLine
      if (data.containsKey('points') || data.containsKey('path')) {
        return FreehandLine.fromJson(data);
      }
      return SimpleLine.fromJson(data);
    case 'FreehandLine':
      return FreehandLine.fromJson(data);
    case 'SmoothLine':
      return SmoothLine.fromJson(data);
    case 'StraightLine':
      return StraightLine.fromJson(data);
    case 'Rectangle':
      return Rectangle.fromJson(data);
    case 'Circle':
      return Circle.fromJson(data);
    case 'Triangle':
      return Triangle.fromJson(data);
    case 'Eraser':
      return Eraser.fromJson(data);
    case 'Lasso':
      return Lasso.fromJson(data);
    case 'TextContent':
      return TextContent.fromJson(data);
    case 'ImageContent':
      return ImageContent.fromJson(data);
    case 'ShapeStickerContent':
      return ShapeStickerContent.fromJson(data);
    case 'GroupContent':
      return GroupContent.fromJson(data);
    case 'FillContent':
      return FillContent.fromJson(data);
    case 'ClippedHistoryContent':
      return ClippedHistoryContent.fromJson(data);
    case 'EraserHole':
      return EraserHole.fromJson(data);
    case 'Eyedropper':
      return Eyedropper.fromJson(data);
    case 'BlurContent':
      return BlurContent.fromJson(data);
    case 'SmudgeContent':
      return SmudgeContent.fromJson(data);
    case 'EmptyContent':
      return EmptyContent.fromJson(data);
    case 'Mirror':
    case 'MirrorContent':
      return MirrorContent.fromJson(data);
    case 'QuadMirror':
    case 'QuadMirrorContent':
      return QuadMirrorContent.fromJson(data);
    case 'Radial':
    case 'RadialContent':
      return RadialContent.fromJson(data);
    case 'Pentagon':
      return Pentagon.fromJson(data);
    case 'Heart':
      return Heart.fromJson(data);
    case 'CubeShape':
      return CubeShape.fromJson(data);
    case 'CylinderShape':
      return CylinderShape.fromJson(data);
    case 'TriangleShape':
      return TriangleShape.fromJson(data);
    case 'RightTriangleShape':
      return RightTriangleShape.fromJson(data);
    case 'DiamondShape':
      return DiamondShape.fromJson(data);
    case 'PentagonShape':
      return PentagonShape.fromJson(data);
    case 'HexagonShape':
      return HexagonShape.fromJson(data);
    case 'StarShape':
      return StarShape.fromJson(data);
    case 'EllipseShape':
      return EllipseShape.fromJson(data);
    case 'RoundedRectShape':
      return RoundedRectShape.fromJson(data);
    case 'ParallelogramShape':
      return ParallelogramShape.fromJson(data);
    case 'TrapezoidShape':
      return TrapezoidShape.fromJson(data);
    case 'CrossShape':
      return CrossShape.fromJson(data);
    case 'LightningShape':
      return LightningShape.fromJson(data);
    case 'HeartShape':
      return HeartShape.fromJson(data);
    case 'SpeechBubbleShape':
      return SpeechBubbleShape.fromJson(data);
    case 'CloudShape':
      return CloudShape.fromJson(data);
    case 'ArrowShape':
      return ArrowShape.fromJson(data);
    case 'DashedLine':
      return DashedLine.fromJson(data);
    case 'DottedLine':
      return DottedLine.fromJson(data);
    case 'HighlighterLine':
      return HighlighterLine.fromJson(data);
    case 'ImageTipBrush':
      return ImageTipBrush.fromJson(data);
    case 'TipBrush':
      return TipBrush.fromJson(data);
    case 'SquareBrush':
      return SquareBrush.fromJson(data);
    case 'DiamondBrush':
      return DiamondBrush.fromJson(data);
    case 'TriangleBrush':
      return TriangleBrush.fromJson(data);
    case 'StarBrush':
      return StarBrush.fromJson(data);
    case 'CalligraphyBrush':
      return CalligraphyBrush.fromJson(data);
    case 'SoftRoundBrush':
      return SoftRoundBrush.fromJson(data);
    case 'HardRoundBrush':
      return HardRoundBrush.fromJson(data);
    case 'AirbrushBrush':
      return AirbrushBrush.fromJson(data);
    case 'ChalkBrush':
      return ChalkBrush.fromJson(data);
    case 'ScatterBrush':
      return ScatterBrush.fromJson(data);
    case 'StrokeRecolorContent':
      return StrokeRecolorContent.fromJson(data, history);
    case 'ShapeFillContent':
      return ShapeFillContent.fromJson(data, history);

    // Preset Strokes (Brush Tips)
    case 'ChoppyLine':
      return ChoppyLine.fromJson(data);
    case 'RoughPenLine':
      return RoughPenLine.fromJson(data);
    case 'InkLine':
      return InkLine.fromJson(data);
    case 'PencilLine':
      return PencilLine.fromJson(data);
    case 'HalftoneLine':
      return HalftoneLine.fromJson(data);
    case 'HatchLine':
      return HatchLine.fromJson(data);
    case 'MosaicLine':
      return MosaicLine.fromJson(data);
    case 'TubeLine':
      return TubeLine.fromJson(data);
    case 'CandyCaneLine':
      return CandyCaneLine.fromJson(data);
    case 'SparklesLine':
      return SparklesLine.fromJson(data);
    case 'SprinklesLine':
      return SprinklesLine.fromJson(data);
    case 'StaticLine':
      return StaticLine.fromJson(data);
    case 'NeonGlowLine':
      return NeonGlowLine.fromJson(data);
    case 'RainbowLine':
      return RainbowLine.fromJson(data);
    case 'RibbonLine':
      return RibbonLine.fromJson(data);
    case 'ConstellationLine':
      return ConstellationLine.fromJson(data);
    case 'ChainLine':
      return ChainLine.fromJson(data);
    case 'ElectricArcLine':
      return ElectricArcLine.fromJson(data);
    case 'BubbleTrailLine':
      return BubbleTrailLine.fromJson(data);
    case 'AudioSpectrumLine':
      return AudioSpectrumLine.fromJson(data);
    case 'StitchLine':
      return StitchLine.fromJson(data);

    // Stroke Styles
    case 'SawLine':
      return SawLine.fromJson(data);
    case 'ZigzagLine':
      return ZigzagLine.fromJson(data);
    case 'GearLine':
      return GearLine.fromJson(data);
    case 'HeartbeatLine':
      return HeartbeatLine.fromJson(data);
    case 'HairLine':
      return HairLine.fromJson(data);
    case 'PixelLine':
      return PixelLine.fromJson(data);
    case 'GradientLine':
      return GradientLine.fromJson(data);
    case 'SketchLine':
      return SketchLine.fromJson(data);

    // Offset & Clipped wrappers
    case 'OffsetContent':
      return OffsetContent.fromJson(data);
    case 'ClippedContent':
      return ClippedContent.fromJson(data);

    default:
      return null;
  }
}
