import 'package:flutter/material.dart';
import '../services/runtime_font_service.dart';

class FontPreset {
  final String name;
  final String? fontFamily;
  final FontWeight fontWeight;
  final FontStyle fontStyle;
  final double letterSpacing;
  final String? fallbackFamily;
  final String category;
  final String styleTag;

  const FontPreset({
    required this.name,
    this.fontFamily,
    this.fontWeight = FontWeight.normal,
    this.fontStyle = FontStyle.normal,
    this.letterSpacing = 0.0,
    this.fallbackFamily,
    this.category = 'Clean & Sans',
    this.styleTag = 'Standard',
  });

  TextStyle getTextStyle({
    required Color color,
    required double fontSize,
    double opacity = 1.0,
    bool forceBold = false,
    bool forceItalic = false,
    bool forceUnderline = false,
  }) {
    final effectiveColor = color.withOpacity(opacity);
    final isLoaded = fontFamily == null ||
        RuntimeFontService.instance.isFontLoaded(fontFamily);

    final effectiveFamily = isLoaded ? fontFamily : (fallbackFamily ?? fontFamily);

    return TextStyle(
      color: effectiveColor,
      fontSize: fontSize,
      fontFamily: effectiveFamily,
      fontWeight: forceBold
          ? FontWeight.bold
          : (fontWeight != FontWeight.normal ? fontWeight : FontWeight.normal),
      fontStyle: forceItalic
          ? FontStyle.italic
          : (fontStyle != FontStyle.normal ? fontStyle : FontStyle.normal),
      decoration: forceUnderline ? TextDecoration.underline : TextDecoration.none,
      decorationColor: effectiveColor,
      letterSpacing: letterSpacing,
    );
  }
}

const List<FontPreset> fontPresets = [
  FontPreset(
    name: 'Alex Brush',
    fontFamily: 'AlexBrush',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Calligraphy',
  ),
  FontPreset(
    name: 'Dancing Script',
    fontFamily: 'DancingScript',
    fontWeight: FontWeight.w700,
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Vibrant Script',
  ),
  FontPreset(
    name: 'Great Vibes',
    fontFamily: 'GreatVibes',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Flowing Calligraphy',
  ),
  FontPreset(
    name: 'Pacifico',
    fontFamily: 'Pacifico',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Surf Script',
  ),
  FontPreset(
    name: 'Lobster',
    fontFamily: 'Lobster',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Retro Bold Script',
  ),
  FontPreset(
    name: 'Satisfy',
    fontFamily: 'Satisfy',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Smooth Brush',
  ),
  FontPreset(
    name: 'Parisienne',
    fontFamily: 'Parisienne',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Parisian Script',
  ),
  FontPreset(
    name: 'Pinyon Script',
    fontFamily: 'PinyonScript',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Vintage Aristocrat',
  ),
  FontPreset(
    name: 'Grand Hotel',
    fontFamily: 'GrandHotel',
    fontWeight: FontWeight.w600,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Upright Classic',
  ),
  FontPreset(
    name: 'Kaushan Script',
    fontFamily: 'KaushanScript',
    fontWeight: FontWeight.w600,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Artistic Brush',
  ),
  FontPreset(
    name: 'Sacramento',
    fontFamily: 'Sacramento',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Monoline Retro',
  ),
  FontPreset(
    name: 'Allura',
    fontFamily: 'Allura',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Delicate Ribbon',
  ),
  FontPreset(
    name: 'Italianno',
    fontFamily: 'Italianno',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Italian Cursive',
  ),
  FontPreset(
    name: 'Tangerine',
    fontFamily: 'Tangerine',
    fontWeight: FontWeight.bold,
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Tall Calligraphy',
  ),
  FontPreset(
    name: 'Courgette',
    fontFamily: 'Courgette',
    fontWeight: FontWeight.w600,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Medium Brush',
  ),
  FontPreset(
    name: 'Yellowtail',
    fontFamily: 'Yellowtail',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Sign Painter Script',
  ),
  FontPreset(
    name: 'Damion',
    fontFamily: 'Damion',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Casual Flow',
  ),
  FontPreset(
    name: 'Cookie',
    fontFamily: 'Cookie',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: '1950s Pin-up Script',
  ),
  FontPreset(
    name: 'Norican',
    fontFamily: 'Norican',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Art Deco Cursive',
  ),
  FontPreset(
    name: 'Berkshire Swash',
    fontFamily: 'BerkshireSwash',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Ornate Swash',
  ),
  FontPreset(
    name: 'Marck Script',
    fontFamily: 'MarckScript',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Fountain Pen',
  ),
  FontPreset(
    name: 'Bad Script',
    fontFamily: 'BadScript',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Everyday Handwriting',
  ),
  FontPreset(
    name: 'Stalemate',
    fontFamily: 'Stalemate',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Vintage Ink Signature',
  ),
  FontPreset(
    name: 'Vibes',
    fontFamily: 'Vibes',
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Modern Flow',
  ),
  FontPreset(
    name: 'Rouge Script',
    fontFamily: 'RougeScript',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Sensual French Script',
  ),
  FontPreset(
    name: 'Rochester',
    fontFamily: 'Rochester',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Victorian Flow',
  ),
  FontPreset(
    name: 'Ruthie',
    fontFamily: 'Ruthie',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Delicate Pen Florid',
  ),
  FontPreset(
    name: 'Sail',
    fontFamily: 'Sail',
    fontWeight: FontWeight.w600,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Nautical Didone Script',
  ),
  FontPreset(
    name: 'Sevillana',
    fontFamily: 'Sevillana',
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Flamenco Andalusian',
  ),
  FontPreset(
    name: 'Yesteryear',
    fontFamily: 'Yesteryear',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: '1940s Hollywood Title',
  ),
  FontPreset(
    name: 'Oleo Script',
    fontFamily: 'OleoScript',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Flowing Non-Connecting',
  ),
  FontPreset(
    name: 'Oleo Script Swash',
    fontFamily: 'OleoScriptSwashCaps',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Decorative Swash Caps',
  ),
  FontPreset(
    name: 'Ruge Boogie',
    fontFamily: 'RugeBoogie',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Expressive Handwriting',
  ),
  FontPreset(
    name: 'Caramel',
    fontFamily: 'Caramel',
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Sweet Casual Script',
  ),
  FontPreset(
    name: 'Cherry Swash',
    fontFamily: 'CherrySwash',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Cherry Swash Script',
  ),
  FontPreset(
    name: 'Dynalight',
    fontFamily: 'Dynalight',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Vintage Baggage Label',
  ),
  FontPreset(
    name: 'Engagement',
    fontFamily: 'Engagement',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Monoline Invitation',
  ),
  FontPreset(
    name: 'Galada',
    fontFamily: 'Galada',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Bengali Lobster Style',
  ),
  FontPreset(
    name: 'Julee',
    fontFamily: 'Julee',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Sweet Handwriting',
  ),
  FontPreset(
    name: 'Kavivanar',
    fontFamily: 'Kavivanar',
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Tamil Handwriting',
  ),
  FontPreset(
    name: 'Praise',
    fontFamily: 'Praise',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Smooth Contemporary',
  ),
  FontPreset(
    name: 'Charmonman',
    fontFamily: 'Charmonman',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Script & Cursive',
    styleTag: 'Formal Thai Flourish',
  ),
  FontPreset(
    name: 'Permanent Marker',
    fontFamily: 'PermanentMarker',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'sans-serif',
    category: 'Handwritten & Casual',
    styleTag: 'Bold Street Marker',
  ),
  FontPreset(
    name: 'Rock Salt',
    fontFamily: 'RockSalt',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Felt Tip Grunge',
  ),
  FontPreset(
    name: 'Indie Flower',
    fontFamily: 'IndieFlower',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Bubbly Carefree Notes',
  ),
  FontPreset(
    name: 'Caveat',
    fontFamily: 'Caveat',
    fontWeight: FontWeight.w700,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Casual Pen Notes',
  ),
  FontPreset(
    name: 'Caveat Brush',
    fontFamily: 'CaveatBrush',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Thick Tip Marker',
  ),
  FontPreset(
    name: 'Kalam',
    fontFamily: 'Kalam',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Fresh Organic Pen',
  ),
  FontPreset(
    name: 'Patrick Hand',
    fontFamily: 'PatrickHand',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Neat Handwriting',
  ),
  FontPreset(
    name: 'Shadows Into Light',
    fontFamily: 'ShadowsIntoLight',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Gentle Clean Script',
  ),
  FontPreset(
    name: 'Homemade Apple',
    fontFamily: 'HomemadeApple',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Chalkboard Cursive',
  ),
  FontPreset(
    name: 'Reenie Beanie',
    fontFamily: 'ReenieBeanie',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Ballpoint Scribble',
  ),
  FontPreset(
    name: 'Architects Daughter',
    fontFamily: 'ArchitectsDaughter',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Blueprint Grid Hand',
  ),
  FontPreset(
    name: 'Covered By Your Grace',
    fontFamily: 'CoveredByYourGrace',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Tall Handwritten',
  ),
  FontPreset(
    name: 'Walter Turncoat',
    fontFamily: 'WalterTurncoat',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Quirky Marker',
  ),
  FontPreset(
    name: 'Kranky',
    fontFamily: 'Kranky',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Playful Handdrawn',
  ),
  FontPreset(
    name: 'Zeyada',
    fontFamily: 'Zeyada',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Expressive Signature',
  ),
  FontPreset(
    name: 'Mountains of Christmas',
    fontFamily: 'MountainsofChristmas',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Holiday Whimsical',
  ),
  FontPreset(
    name: 'Amatic SC',
    fontFamily: 'AmaticSC',
    fontWeight: FontWeight.bold,
    letterSpacing: 2.0,
    fallbackFamily: 'sans-serif',
    category: 'Handwritten & Casual',
    styleTag: 'Tall Condensed Caps',
  ),
  FontPreset(
    name: 'ComicNeue Bold',
    fontFamily: 'ComicNeue-Bold',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'sans-serif',
    category: 'Handwritten & Casual',
    styleTag: 'Friendly Comic Bold',
  ),
  FontPreset(
    name: 'Henny Penny',
    fontFamily: 'HennyPenny',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Bouncy Cartoon',
  ),
  FontPreset(
    name: 'The Girl Next Door',
    fontFamily: 'TheGirlNextDoor',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Sweet Girl Handwriting',
  ),
  FontPreset(
    name: 'Sunshiney',
    fontFamily: 'Sunshiney',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Sunny Cheerful Felt',
  ),
  FontPreset(
    name: 'Love Ya Like A Sister',
    fontFamily: 'LoveYaLikeASister',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Hearty Pencil Doodle',
  ),
  FontPreset(
    name: 'Cabin Sketch',
    fontFamily: 'CabinSketch',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'sans-serif',
    category: 'Handwritten & Casual',
    styleTag: 'Crosshatched Sketch',
  ),
  FontPreset(
    name: 'Gaegu',
    fontFamily: 'Gaegu',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Cute Korean Hand',
  ),
  FontPreset(
    name: 'Gamja Flower',
    fontFamily: 'GamjaFlower',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Flower Handdrawn',
  ),
  FontPreset(
    name: 'Hi Melody',
    fontFamily: 'HiMelody',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Singing Notes Hand',
  ),
  FontPreset(
    name: 'Hachi Maru Pop',
    fontFamily: 'HachiMaruPop',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: '80s Japanese Pop Kawaii',
  ),
  FontPreset(
    name: 'Grandstander',
    fontFamily: 'Grandstander',
    fontWeight: FontWeight.w700,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Fun Rounded Hand',
  ),
  FontPreset(
    name: 'Gluten',
    fontFamily: 'Gluten',
    fontWeight: FontWeight.w800,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Puffy Bread Dough',
  ),
  FontPreset(
    name: 'Jua',
    fontFamily: 'Jua',
    fallbackFamily: 'sans-serif',
    category: 'Handwritten & Casual',
    styleTag: 'Chubby Korean Retro',
  ),
  FontPreset(
    name: 'Kirang Haerang',
    fontFamily: 'KirangHaerang',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Dramatic Brush Strokes',
  ),
  FontPreset(
    name: 'Pangolin',
    fontFamily: 'Pangolin',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Cute Playful Handwriting',
  ),
  FontPreset(
    name: 'Mali',
    fontFamily: 'Mali',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Happy Thai Handwriting',
  ),
  FontPreset(
    name: 'Gochi Hand',
    fontFamily: 'GochiHand',
    fallbackFamily: 'cursive',
    category: 'Handwritten & Casual',
    styleTag: 'Teenage Marker Note',
  ),
  FontPreset(
    name: 'Bebas Neue',
    fontFamily: 'BebasNeue',
    fontWeight: FontWeight.w900,
    letterSpacing: 1.5,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Headline Master',
  ),
  FontPreset(
    name: 'Anton',
    fontFamily: 'Anton',
    fontWeight: FontWeight.w900,
    letterSpacing: 0.5,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Heavy Impact Poster',
  ),
  FontPreset(
    name: 'Oswald',
    fontFamily: 'Oswald',
    fontWeight: FontWeight.w700,
    letterSpacing: 1.0,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Classic Gothic Condensed',
  ),
  FontPreset(
    name: 'Alfa Slab One',
    fontFamily: 'AlfaSlabOne',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'serif',
    category: 'Bold & Display',
    styleTag: 'Ultra Slab Heavy',
  ),
  FontPreset(
    name: 'Ultra',
    fontFamily: 'Ultra',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'serif',
    category: 'Bold & Display',
    styleTag: 'Mega Bold Woodtype',
  ),
  FontPreset(
    name: 'Black Ops One',
    fontFamily: 'BlackOpsOne',
    fontWeight: FontWeight.bold,
    letterSpacing: 1.0,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Military Stencil',
  ),
  FontPreset(
    name: 'Bangers',
    fontFamily: 'Bangers',
    fontWeight: FontWeight.w900,
    letterSpacing: 1.0,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Comic Superhero Punch',
  ),
  FontPreset(
    name: 'Luckiest Guy',
    fontFamily: 'LuckiestGuy',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: '1950s Custom Ad',
  ),
  FontPreset(
    name: 'Titan One',
    fontFamily: 'TitanOne',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Chubby Rounded Title',
  ),
  FontPreset(
    name: 'Lilita One',
    fontFamily: 'LilitaOne',
    fontWeight: FontWeight.w800,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Chunky Soft Poster',
  ),
  FontPreset(
    name: 'Rowdies',
    fontFamily: 'Rowdies',
    fontWeight: FontWeight.w800,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Action Bollywood Title',
  ),
  FontPreset(
    name: 'Russo One',
    fontFamily: 'RussoOne',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Constructivist Block Bold',
  ),
  FontPreset(
    name: 'Knewave',
    fontFamily: 'Knewave',
    fontWeight: FontWeight.bold,
    fontStyle: FontStyle.italic,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Painted Brush Bold',
  ),
  FontPreset(
    name: 'Lemon',
    fontFamily: 'Lemon',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Bold & Display',
    styleTag: 'Zesty Bold Retro',
  ),
  FontPreset(
    name: 'Limelight',
    fontFamily: 'Limelight',
    fallbackFamily: 'serif',
    category: 'Bold & Display',
    styleTag: '1920s Art Deco Cinema',
  ),
  FontPreset(
    name: 'Londrina Solid',
    fontFamily: 'LondrinaSolid',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Urban Rounded Block',
  ),
  FontPreset(
    name: 'Londrina Outline',
    fontFamily: 'LondrinaOutline',
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Urban Outline Poster',
  ),
  FontPreset(
    name: 'Londrina Shadow',
    fontFamily: 'LondrinaShadow',
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Urban 3D Shadow',
  ),
  FontPreset(
    name: 'Londrina Sketch',
    fontFamily: 'LondrinaSketch',
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Urban Hand Sketch',
  ),
  FontPreset(
    name: 'Oi',
    fontFamily: 'Oi',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'serif',
    category: 'Bold & Display',
    styleTag: 'Super Chubby Fat Serif',
  ),
  FontPreset(
    name: 'Passion One',
    fontFamily: 'PassionOne',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Ultra Heavy Headline',
  ),
  FontPreset(
    name: 'Patua One',
    fontFamily: 'PatuaOne',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Bold & Display',
    styleTag: 'Caribbean Slab Poster',
  ),
  FontPreset(
    name: 'Paytone One',
    fontFamily: 'PaytoneOne',
    fontWeight: FontWeight.w800,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Casual Modern Headline',
  ),
  FontPreset(
    name: 'Peralta',
    fontFamily: 'Peralta',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Bold & Display',
    styleTag: 'Comic Serif Headline',
  ),
  FontPreset(
    name: 'Piedra',
    fontFamily: 'Piedra',
    fallbackFamily: 'serif',
    category: 'Bold & Display',
    styleTag: 'Chiseled Stone Slab',
  ),
  FontPreset(
    name: 'Poller One',
    fontFamily: 'PollerOne',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Early 20th Century Poster',
  ),
  FontPreset(
    name: 'Racing Sans One',
    fontFamily: 'RacingSansOne',
    fontWeight: FontWeight.w900,
    fontStyle: FontStyle.italic,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'High Speed Motorsport',
  ),
  FontPreset(
    name: 'Rock 3D',
    fontFamily: 'Rock3D',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: '3D Extruded Stone',
  ),
  FontPreset(
    name: 'RocknRoll One',
    fontFamily: 'RocknRollOne',
    fontWeight: FontWeight.w700,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Japanese Rock Music',
  ),
  FontPreset(
    name: 'Rozha One',
    fontFamily: 'RozhaOne',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'serif',
    category: 'Bold & Display',
    styleTag: 'High Contrast Didone Fat',
  ),
  FontPreset(
    name: 'Shrikhand',
    fontFamily: 'Shrikhand',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Retro 70s Groovy',
  ),
  FontPreset(
    name: 'Modak',
    fontFamily: 'Modak',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Inflatable Balloon',
  ),
  FontPreset(
    name: 'Bungee',
    fontFamily: 'Bungee',
    fontWeight: FontWeight.w800,
    letterSpacing: 1.0,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Urban Vertical Sign',
  ),
  FontPreset(
    name: 'Bungee Shade',
    fontFamily: 'BungeeShade',
    fontWeight: FontWeight.w800,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: '3D Chromatic Shadow',
  ),
  FontPreset(
    name: 'Bungee Inline',
    fontFamily: 'BungeeInline',
    fontWeight: FontWeight.w800,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Dual Outline Urban',
  ),
  FontPreset(
    name: 'Fugaz One',
    fontFamily: 'FugazOne',
    fontWeight: FontWeight.w900,
    fontStyle: FontStyle.italic,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Dynamic Speed Italic',
  ),
  FontPreset(
    name: 'Poetsen One',
    fontFamily: 'PoetsenOne',
    fontWeight: FontWeight.w700,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Handcrafted Poster',
  ),
  FontPreset(
    name: 'Cherry Cream Soda',
    fontFamily: 'CherryCreamSoda',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Bold & Display',
    styleTag: 'Vintage Diner Fun',
  ),
  FontPreset(
    name: 'Fontdiner Swanky',
    fontFamily: 'FontdinerSwanky',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Bold & Display',
    styleTag: 'Retro 1960s TV Show',
  ),
  FontPreset(
    name: 'Gorditas',
    fontFamily: 'Gorditas',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Bold & Display',
    styleTag: 'Sweet Chunky Rounded',
  ),
  FontPreset(
    name: 'Sniglet',
    fontFamily: 'Sniglet',
    fontWeight: FontWeight.w800,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Cartoon Bubble Title',
  ),
  FontPreset(
    name: 'Sonsie One',
    fontFamily: 'SonsieOne',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'cursive',
    category: 'Bold & Display',
    styleTag: 'Painted Sign Title',
  ),
  FontPreset(
    name: 'Trade Winds',
    fontFamily: 'TradeWinds',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Bold & Display',
    styleTag: 'Tiki Tropical',
  ),
  FontPreset(
    name: 'Vast Shadow',
    fontFamily: 'VastShadow',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Bold & Display',
    styleTag: 'Victorian Slab Shadow',
  ),
  FontPreset(
    name: 'Faster One',
    fontFamily: 'FasterOne',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Racing Speed Lines',
  ),
  FontPreset(
    name: 'Ranchers',
    fontFamily: 'Ranchers',
    fontWeight: FontWeight.w800,
    fallbackFamily: 'cursive',
    category: 'Bold & Display',
    styleTag: 'Retro Circus Slab',
  ),
  FontPreset(
    name: 'Rammetto One',
    fontFamily: 'RammettoOne',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Italian Block Display',
  ),
  FontPreset(
    name: 'Chicle',
    fontFamily: 'Chicle',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Bold & Display',
    styleTag: 'Chewing Gum Playful',
  ),
  FontPreset(
    name: 'Carter One',
    fontFamily: 'CarterOne',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Casual Bold Sans',
  ),
  FontPreset(
    name: 'Chango',
    fontFamily: 'Chango',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Short Heavy Block',
  ),
  FontPreset(
    name: 'Chela One',
    fontFamily: 'ChelaOne',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Bold & Display',
    styleTag: 'Bold Brush Headline',
  ),
  FontPreset(
    name: 'Coiny',
    fontFamily: 'Coiny',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Bold & Display',
    styleTag: 'Chubby Rounded Block',
  ),
  FontPreset(
    name: 'Playfair Display',
    fontFamily: 'PlayfairDisplay',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Vogue Luxury Editorial',
  ),
  FontPreset(
    name: 'Abril Fatface',
    fontFamily: 'AbrilFatface',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Fashion Poster Serif',
  ),
  FontPreset(
    name: 'Cinzel',
    fontFamily: 'Cinzel',
    fontWeight: FontWeight.bold,
    letterSpacing: 1.5,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Roman Stone Inscription',
  ),
  FontPreset(
    name: 'Cinzel Decorative',
    fontFamily: 'CinzelDecorative',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Ornate Royal Crest',
  ),
  FontPreset(
    name: 'DM Serif Display',
    fontFamily: 'DMSerifDisplay',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'High Contrast Book',
  ),
  FontPreset(
    name: 'EB Garamond',
    fontFamily: 'EBGaramond',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Renaissance Master',
  ),
  FontPreset(
    name: 'Lora',
    fontFamily: 'Lora',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Contemporary Literary',
  ),
  FontPreset(
    name: 'MedievalSharp',
    fontFamily: 'MedievalSharp',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Gothic Fantasy Codex',
  ),
  FontPreset(
    name: 'UnifrakturMaguntia',
    fontFamily: 'UnifrakturMaguntia',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Authentic Blackletter',
  ),
  FontPreset(
    name: 'UnifrakturCook',
    fontFamily: 'UnifrakturCook',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Dark Medieval Gothic',
  ),
  FontPreset(
    name: 'Pirata One',
    fontFamily: 'PirataOne',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Pirate Gothic Scroll',
  ),
  FontPreset(
    name: 'Almendra Display',
    fontFamily: 'AlmendraDisplay',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Fairytale Medieval',
  ),
  FontPreset(
    name: 'Rye',
    fontFamily: 'Rye',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Wild West Woodtype',
  ),
  FontPreset(
    name: 'Germania One',
    fontFamily: 'GermaniaOne',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Historic European Slab',
  ),
  FontPreset(
    name: 'Glass Antiqua',
    fontFamily: 'GlassAntiqua',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Art Nouveau Antiqua',
  ),
  FontPreset(
    name: 'Milonga',
    fontFamily: 'Milonga',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Tango Argentine Flair',
  ),
  FontPreset(
    name: 'Sancreek',
    fontFamily: 'Sancreek',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Vintage Saloon Western',
  ),
  FontPreset(
    name: 'Spirax',
    fontFamily: 'Spirax',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Curved Whimsical Serif',
  ),
  FontPreset(
    name: 'Trochut',
    fontFamily: 'Trochut',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Catalan Romanesque',
  ),
  FontPreset(
    name: 'Quattrocento',
    fontFamily: 'Quattrocento',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Italian Renaissance Roman',
  ),
  FontPreset(
    name: 'Radley',
    fontFamily: 'Radley',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Handcarved Wood Serif',
  ),
  FontPreset(
    name: 'Bevan',
    fontFamily: 'Bevan',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: '1930s Slab Serif',
  ),
  FontPreset(
    name: 'Calistoga',
    fontFamily: 'Calistoga',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Cheerful Warm Slab',
  ),
  FontPreset(
    name: 'Corben',
    fontFamily: 'Corben',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Curvaceous Display Serif',
  ),
  FontPreset(
    name: 'Coustard',
    fontFamily: 'Coustard',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Heavyweight Slab Serif',
  ),
  FontPreset(
    name: 'Diplomata',
    fontFamily: 'Diplomata',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Opulent Wide Shadow',
  ),
  FontPreset(
    name: 'Diplomata SC',
    fontFamily: 'DiplomataSC',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Engraved Royal Caps',
  ),
  FontPreset(
    name: 'Ewert',
    fontFamily: 'Ewert',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Carnival Ornamental Slab',
  ),
  FontPreset(
    name: 'Federant',
    fontFamily: 'Federant',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Bookman Renaissance',
  ),
  FontPreset(
    name: 'Girassol',
    fontFamily: 'Girassol',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Portuguese Road Sign',
  ),
  FontPreset(
    name: 'Glegoo',
    fontFamily: 'Glegoo',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Balanced Modern Slab',
  ),
  FontPreset(
    name: 'Gloock',
    fontFamily: 'Gloock',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'High Contrast Editorial',
  ),
  FontPreset(
    name: 'Gravitas One',
    fontFamily: 'GravitasOne',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Heavy British Fat Face',
  ),
  FontPreset(
    name: 'Grenze Gotisch',
    fontFamily: 'GrenzeGotisch',
    fontWeight: FontWeight.w800,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Hybrid Blackletter',
  ),
  FontPreset(
    name: 'Headland One',
    fontFamily: 'HeadlandOne',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'English Country Manor',
  ),
  FontPreset(
    name: 'IMFell English SC',
    fontFamily: 'IMFellEnglishSC',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: '17th Century Antique Type',
  ),
  FontPreset(
    name: 'IMFell Double Pica',
    fontFamily: 'IMFellDoublePica',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Oxford Historic Press',
  ),
  FontPreset(
    name: 'Uncial Antiqua',
    fontFamily: 'UncialAntiqua',
    fallbackFamily: 'serif',
    category: 'Serif & Elegant',
    styleTag: 'Celtic Manuscript Uncial',
  ),
  FontPreset(
    name: 'Montserrat',
    fontFamily: 'Montserrat',
    fontWeight: FontWeight.w600,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Modern Geometric Sans',
  ),
  FontPreset(
    name: 'Poppins',
    fontFamily: 'Poppins',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Geometric Round Perfection',
  ),
  FontPreset(
    name: 'Raleway',
    fontFamily: 'Raleway',
    fontWeight: FontWeight.w500,
    letterSpacing: 1.0,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Elegant Ultra-Clean',
  ),
  FontPreset(
    name: 'League Spartan',
    fontFamily: 'LeagueSpartan',
    fontWeight: FontWeight.w800,
    letterSpacing: 0.5,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Geometric Bold Sans',
  ),
  FontPreset(
    name: 'Quicksand',
    fontFamily: 'Quicksand',
    fontWeight: FontWeight.w700,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Friendly Rounded Clean',
  ),
  FontPreset(
    name: 'Comfortaa',
    fontFamily: 'Comfortaa',
    fontWeight: FontWeight.w700,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Rounded Modernist',
  ),
  FontPreset(
    name: 'Fredoka',
    fontFamily: 'Fredoka',
    fontWeight: FontWeight.w600,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Soft Friendly Rounded',
  ),
  FontPreset(
    name: 'Exo Bold',
    fontFamily: 'Exo-Bold',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Futuristic High-Tech',
  ),
  FontPreset(
    name: 'Questrial',
    fontFamily: 'Questrial',
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Circle Geometric Book',
  ),
  FontPreset(
    name: 'Alegreya Sans',
    fontFamily: 'AlegreyaSans',
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Dynamic Humanist Sans',
  ),
  FontPreset(
    name: 'Poiret One',
    fontFamily: 'PoiretOne',
    letterSpacing: 2.0,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Art Deco Geometric Line',
  ),
  FontPreset(
    name: 'Pompiere',
    fontFamily: 'Pompiere',
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Tall Quirky Sans',
  ),
  FontPreset(
    name: 'Syne',
    fontFamily: 'Syne',
    fontWeight: FontWeight.w800,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Avant-Garde Art Exhibition',
  ),
  FontPreset(
    name: 'Play',
    fontFamily: 'Play',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Industrial Modern Square',
  ),
  FontPreset(
    name: 'Rajdhani',
    fontFamily: 'Rajdhani',
    fontWeight: FontWeight.w700,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Square Futuristic UI',
  ),
  FontPreset(
    name: 'Aclonica',
    fontFamily: 'Aclonica',
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Rounded Deco Sans',
  ),
  FontPreset(
    name: 'Baloo 2',
    fontFamily: 'Baloo2',
    fontWeight: FontWeight.w800,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Warm Indian Rounded',
  ),
  FontPreset(
    name: 'Baumans',
    fontFamily: 'Baumans',
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Bauhaus Geometric Arc',
  ),
  FontPreset(
    name: 'Black Han Sans',
    fontFamily: 'BlackHanSans',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Heavy Korean Block',
  ),
  FontPreset(
    name: 'Boogaloo',
    fontFamily: 'Boogaloo',
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: '1960s Vinyl Album Cover',
  ),
  FontPreset(
    name: 'Cagliostro',
    fontFamily: 'Cagliostro',
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Hand-lettered Art Nouveau',
  ),
  FontPreset(
    name: 'Chau Philomene One',
    fontFamily: 'ChauPhilomeneOne',
    fontStyle: FontStyle.italic,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Early 20th C. Ambulance Sign',
  ),
  FontPreset(
    name: 'Contrail One',
    fontFamily: 'ContrailOne',
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Aviation Pilot Instrument',
  ),
  FontPreset(
    name: 'Do Hyeon',
    fontFamily: 'DoHyeon',
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Square Korean Signboard',
  ),
  FontPreset(
    name: 'Flamenco',
    fontFamily: 'Flamenco',
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Graceful Spanish Sans',
  ),
  FontPreset(
    name: 'Galindo',
    fontFamily: 'Galindo',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Super Chubby Rounded',
  ),
  FontPreset(
    name: 'Graduate',
    fontFamily: 'Graduate',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Varsity College Campus',
  ),
  FontPreset(
    name: 'Gruppo',
    fontFamily: 'Gruppo',
    letterSpacing: 2.0,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Minimalist Fashion Wire',
  ),
  FontPreset(
    name: 'Hammersmith One',
    fontFamily: 'HammersmithOne',
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'British Craftsman Title',
  ),
  FontPreset(
    name: 'Jura',
    fontFamily: 'Jura',
    fontWeight: FontWeight.w600,
    fallbackFamily: 'sans-serif',
    category: 'Clean & Sans',
    styleTag: 'Kaypro Terminal Geometric',
  ),
  FontPreset(
    name: 'Righteous',
    fontFamily: 'Righteous',
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Retro Wave Synth',
  ),
  FontPreset(
    name: 'Press Start 2P',
    fontFamily: 'PressStart2P',
    letterSpacing: 1.0,
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: '8-Bit Arcade Pixel',
  ),
  FontPreset(
    name: 'Silkscreen',
    fontFamily: 'Silkscreen',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Clean LCD Game Pixel',
  ),
  FontPreset(
    name: 'VT323',
    fontFamily: 'VT323',
    letterSpacing: 1.5,
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Vintage Terminal CRT',
  ),
  FontPreset(
    name: 'Special Elite',
    fontFamily: 'SpecialElite',
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Vintage Typewriter Ink',
  ),
  FontPreset(
    name: 'Monoton',
    fontFamily: 'Monoton',
    letterSpacing: 1.0,
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Disco Neon Lines',
  ),
  FontPreset(
    name: 'Orbitron',
    fontFamily: 'Orbitron',
    fontWeight: FontWeight.w800,
    letterSpacing: 1.5,
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Futuristic Sci-Fi HUD',
  ),
  FontPreset(
    name: 'Oxanium',
    fontFamily: 'Oxanium',
    fontWeight: FontWeight.w700,
    letterSpacing: 0.5,
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Esports Gaming HUD',
  ),
  FontPreset(
    name: 'Audiowide',
    fontFamily: 'Audiowide',
    fontWeight: FontWeight.w600,
    letterSpacing: 1.0,
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Cyberpunk Synth Tech',
  ),
  FontPreset(
    name: 'Rubik Glitch',
    fontFamily: 'RubikGlitch',
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Digital Cyber Glitch',
  ),
  FontPreset(
    name: 'Rubik Glitch Pop',
    fontFamily: 'RubikGlitchPop',
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Chromatic Neon Glitch',
  ),
  FontPreset(
    name: 'Rubik Beastly',
    fontFamily: 'RubikBeastly',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Monster Fur Texture',
  ),
  FontPreset(
    name: 'Rubik Distressed',
    fontFamily: 'RubikDistressed',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Distressed Stamped Ink',
  ),
  FontPreset(
    name: 'Rubik Moonrocks',
    fontFamily: 'RubikMoonrocks',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Crater Moon Texture',
  ),
  FontPreset(
    name: 'Rubik Puddles',
    fontFamily: 'RubikPuddles',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Liquid Splash Effect',
  ),
  FontPreset(
    name: 'Rubik Vinyl',
    fontFamily: 'RubikVinyl',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Retro Vinyl Record Groove',
  ),
  FontPreset(
    name: 'Rubik Iso',
    fontFamily: 'RubikIso',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Isometric 3D Cube',
  ),
  FontPreset(
    name: 'Rubik Lines',
    fontFamily: 'RubikLines',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Laser Striped Scanlines',
  ),
  FontPreset(
    name: 'Rubik Pixels',
    fontFamily: 'RubikPixels',
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Chunky Pixel Grid',
  ),
  FontPreset(
    name: 'Rubik Microbe',
    fontFamily: 'RubikMicrobe',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Organic Bio-Cells',
  ),
  FontPreset(
    name: 'Rubik Wet Paint',
    fontFamily: 'RubikWetPaint',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Wet Paint Drip',
  ),
  FontPreset(
    name: 'Rubik 80s Fade',
    fontFamily: 'Rubik80sFade',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: '80s Synthwave Gradient',
  ),
  FontPreset(
    name: 'Rubik Bubbles',
    fontFamily: 'RubikBubbles',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Floating Bubble Spheres',
  ),
  FontPreset(
    name: 'Rubik Doodle Shadow',
    fontFamily: 'RubikDoodleShadow',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Hand Drawn Shadow Hatch',
  ),
  FontPreset(
    name: 'Rubik Gemstones',
    fontFamily: 'RubikGemstones',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Faceted Crystal Gems',
  ),
  FontPreset(
    name: 'Rubik Marker Hatch',
    fontFamily: 'RubikMarkerHatch',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Crosshatch Highlighter',
  ),
  FontPreset(
    name: 'Rubik Maze',
    fontFamily: 'RubikMaze',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Labyrinth Maze Puzzle',
  ),
  FontPreset(
    name: 'Rubik Scribble',
    fontFamily: 'RubikScribble',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Energetic Line Scribble',
  ),
  FontPreset(
    name: 'Rubik Spray Paint',
    fontFamily: 'RubikSprayPaint',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Aerosol Stencil Spray',
  ),
  FontPreset(
    name: 'Rubik Storm',
    fontFamily: 'RubikStorm',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Lightning Thunder Storm',
  ),
  FontPreset(
    name: 'Neonderthaw',
    fontFamily: 'Neonderthaw',
    fallbackFamily: 'cursive',
    category: 'Retro & Cyber',
    styleTag: 'Glowing Neon Tube Script',
  ),
  FontPreset(
    name: 'Road Rage',
    fontFamily: 'RoadRage',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Mad Max Punk Grunge',
  ),
  FontPreset(
    name: 'Revalia',
    fontFamily: 'Revalia',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Art Deco Geometric Stencil',
  ),
  FontPreset(
    name: 'Quantico',
    fontFamily: 'Quantico',
    fontWeight: FontWeight.bold,
    letterSpacing: 1.0,
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Angular Military Tech',
  ),
  FontPreset(
    name: 'Lacquer',
    fontFamily: 'Lacquer',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Melting Toxic Slime',
  ),
  FontPreset(
    name: 'Creepster',
    fontFamily: 'Creepster',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Retro & Cyber',
    styleTag: 'Horror Monster Slime',
  ),
  FontPreset(
    name: 'Nosifer',
    fontFamily: 'Nosifer',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Retro & Cyber',
    styleTag: 'Dripping Blood Splatter',
  ),
  FontPreset(
    name: 'Major Mono Display',
    fontFamily: 'MajorMonoDisplay',
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Abstract Avant Mono',
  ),
  FontPreset(
    name: 'Megrim',
    fontFamily: 'Megrim',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Geometric Wireframe Line',
  ),
  FontPreset(
    name: 'Plaster',
    fontFamily: 'Plaster',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Constructivist Block',
  ),
  FontPreset(
    name: 'Wallpoet',
    fontFamily: 'Wallpoet',
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Cyber Digital Clock Stencil',
  ),
  FontPreset(
    name: 'Geostar Fill',
    fontFamily: 'GeostarFill',
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Geometric Matrix Stencil',
  ),
  FontPreset(
    name: 'Kelly Slab',
    fontFamily: 'KellySlab',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Square Tech Slab',
  ),
  FontPreset(
    name: 'Akronim',
    fontFamily: 'Akronim',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Futuristic Grid Gridlines',
  ),
  FontPreset(
    name: 'Atomic Age',
    fontFamily: 'AtomicAge',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: '1950s Atomic Space Age',
  ),
  FontPreset(
    name: 'Bungee Hairline',
    fontFamily: 'BungeeHairline',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Ultra Thin Urban Wire',
  ),
  FontPreset(
    name: 'Butcherman',
    fontFamily: 'Butcherman',
    fallbackFamily: 'cursive',
    category: 'Retro & Cyber',
    styleTag: 'Spooky Horror Bone Display',
  ),
  FontPreset(
    name: 'Eater',
    fontFamily: 'Eater',
    fallbackFamily: 'cursive',
    category: 'Retro & Cyber',
    styleTag: 'Zombie Monster Decay',
  ),
  FontPreset(
    name: 'Emblema One',
    fontFamily: 'EmblemaOne',
    fallbackFamily: 'cursive',
    category: 'Retro & Cyber',
    styleTag: 'Vintage Stencil Trademark',
  ),
  FontPreset(
    name: 'Fascinate',
    fontFamily: 'Fascinate',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Art Deco Broadway Show',
  ),
  FontPreset(
    name: 'Fascinate Inline',
    fontFamily: 'FascinateInline',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Broadway Illuminated Marquee',
  ),
  FontPreset(
    name: 'Flavors',
    fontFamily: 'Flavors',
    fallbackFamily: 'cursive',
    category: 'Retro & Cyber',
    styleTag: 'Psychedelic Swirl 1970s',
  ),
  FontPreset(
    name: 'Frijole',
    fontFamily: 'Frijole',
    fallbackFamily: 'cursive',
    category: 'Retro & Cyber',
    styleTag: 'Spicy Bean Cartoon',
  ),
  FontPreset(
    name: 'Fruktur',
    fontFamily: 'Fruktur',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'serif',
    category: 'Retro & Cyber',
    styleTag: 'Juicy Blocky Woodcut',
  ),
  FontPreset(
    name: 'Iceberg',
    fontFamily: 'Iceberg',
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Glacial Modular Tech',
  ),
  FontPreset(
    name: 'Iceland',
    fontFamily: 'Iceland',
    letterSpacing: 1.0,
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Angular Sci-Fi Grid',
  ),
  FontPreset(
    name: 'Inconsolata',
    fontFamily: 'Inconsolata',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Hacker Code Monospace',
  ),
  FontPreset(
    name: 'Jacquard 12',
    fontFamily: 'Jacquard12',
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'Woven Loom Pixel Tapestry',
  ),
  FontPreset(
    name: 'Jacquard 24',
    fontFamily: 'Jacquard24',
    fallbackFamily: 'monospace',
    category: 'Retro & Cyber',
    styleTag: 'High-Res Pixel Weave',
  ),
  FontPreset(
    name: 'Jolly Lodger',
    fontFamily: 'JollyLodger',
    fallbackFamily: 'cursive',
    category: 'Retro & Cyber',
    styleTag: 'Haunted Mansion Spooky',
  ),
  FontPreset(
    name: 'Keania One',
    fontFamily: 'KeaniaOne',
    fontWeight: FontWeight.bold,
    fallbackFamily: 'cursive',
    category: 'Retro & Cyber',
    styleTag: 'Artistic Stencil Display',
  ),
  FontPreset(
    name: 'Climate Crisis',
    fontFamily: 'ClimateCrisis',
    fontWeight: FontWeight.w900,
    fallbackFamily: 'sans-serif',
    category: 'Retro & Cyber',
    styleTag: 'Glacial Melt Display',
  ),
];

FontPreset getFontPresetByName(String? name) {
  if (name == null || name.isEmpty) return fontPresets.first;
  return fontPresets.firstWhere(
    (preset) => preset.name == name || preset.fontFamily == name,
    orElse: () => fontPresets.first,
  );
}

